[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = true

[context.production.environment]
  TOML_ENV_VAR = "From netlify.toml"
  REACT_APP_TOML_ENV_VAR = "From netlify.toml (REACT_APP_)"